### ISSUE TITLE
Beemod Exporting process is now totally broken: Full Export is not copying resources to the game

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#532]
Proof of this is that the Puzzle Editor wouldn´t change textures when using Overgrown, Old Ap, Etc...As well as many items that are working pretty weird like the case of the PeTi Glass/Grating becoming "Thin Walls".......

Edited: I do not had Hammer Open while this process.

![20170223101255_1](https://cloud.githubusercontent.com/assets/12244376/23260487/ccd8ef96-f9b0-11e6-9309-0bd69f910936.jpg)

_______________________________________________________________________________

Also, sometimes beemod "Skipps" half part of the exporting process as i were having the "Preserve game dir" enabled when its not.... See this:

![Export](https://cloud.githubusercontent.com/assets/12244376/23261210/09091376-f9b4-11e6-8f81-50606cc1e330.png)

**Comment by LautaroL20** [comment]
Also, sometimes beemod "Skipps" half part of the exporting process as i were having the "Preserve game dir" enabled when its not.... See this:

![Export](https://cloud.githubusercontent.com/assets/12244376/23261210/09091376-f9b4-11e6-8f81-50606cc1e330.png)

**Comment by LautaroL20** [comment]
Luckily, ive maded a backpup from the "BEE2.4" folder before Sync with Github, so no need to downgrade to the PRL24.

**Comment by TeamSpen210** [comment]
Are you using zip files, or folders? With zips it should skip extracting if it detects they haven't been edited.

**Comment by LautaroL20** [comment]
Im using zip files, but the thing is how people will manage to copy the packages resources to the game when PRL25 comes out if now beemod skips this process?

**Comment by TeamSpen210** [comment]
It should only extract once, then reuse the files.

**Comment by LautaroL20** [comment]
@TeamSpen210 - I need a pair of glasses, i don´t really use zip files since the Development Version uses folders. I had probably a mental lapsus where i thought i were using a PRL when i wrote ive been using "zip files". 

Please, take a look at this issue in order to fix it because i can no longer copy resurces to the game if i Sync with Github.

**Comment by TeamSpen210** [comment]
Should be fixed via 4a322d2efe4e682f3274aa2fd411ec5bbca2e198.

**Comment by LautaroL20** [comment]
Ive test it and now there are two problems. After the very first export, each time you change the Style or something in the Palette and hit the export button, it always do a "Full Export" instead of skip the Resources and Music from Progress Bars. Second issue is that the Puzzlemaker´s tiles textures still does not change when set to another Style.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Well this issue in concrete is now fixed... but now there are two new ones: https://github.com/BEEmod/BEE2.4/issues/533 and https://github.com/BEEmod/BEE2.4/issues/534
