### ISSUE TITLE
Maps will not compile outside of Portal 1 Style-PR28

### ISSUE THREAD

**Issue by SputumChucker** [BEEmod/BEE2.4#846]
The issue is, in essence, solely in the title. If I don't have the style set to Portal 1, the game spits out the "there was an error while compiling the map" message right as it finishes the first bar of three. I've done a fresh install of both the game and beemod, but nothing seems to fix it. I'm unsure what logs to provide to help get to the bottom of this issue.

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Note: if for some weird reason, all the instructions above did not solve your issue, please reply to this comment and i will re-open your issue report again, as well as figuring out another solution for your issue, together.**

**Comment by TeamSpen210** [comment]
@LautaroL20 really, this won't solve many issues and shouldn't be necessary anymore.SputumChucker, open the developer console. What's in there?

**Comment by LautaroL20** [comment]
Not true. However, if you want to keep issues like this open is fine, ill not close these issues anymore, but ill keep recommending my suggestions to help users solving their issues though. I am aware of the cause my tips help solving many issues.

**Comment by t1211** [comment]
please reopen mine then, as i have both current versions and have done everything and my problem isnt fixed, so obviously my issue is not that.

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
